theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
name: "Dmytro Tymoshenko"

title: Bacterial Genome Assembly & Procesing Pipeline
description: This page is devoted to the obtained by me knowledge during the work with Xi Zhang <a href="https://github.com/zx0223winner">Xi Zhang</a> on genome assembly & its analysis
